### ISSUE TITLE
jo,开启vssr后，手机端很多网页打不开，而且电脑网页上图片也不能正常显示，请见截图！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#10]
使用ssrplus、openclash和passwall就正常。。。。所以暂时放弃了。。。
![YP)QV7YPJ6JLWMNQ1}R32RD](https://user-images.githubusercontent.com/45259624/75447764-f8173300-59a4-11ea-8531-8c3326311804.png)
![AA%HX%0HHA3 YQLU44PWI)D](https://user-images.githubusercontent.com/45259624/75447774-fcdbe700-59a4-11ea-8e52-c56037c6a72a.png)

**Comment by Ameykyl** [comment]
应该是AD规则起效果了

**Comment by Ameykyl** [comment]
可以把AD规则删掉
