### ISSUE TITLE
Jo,最新版本出现使用gfw模式无法科学打开github，实际已经科学了！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#12]
![image](https://user-images.githubusercontent.com/45259624/75514806-54289880-5a33-11ea-9030-49a029a85be0.png)
![image](https://user-images.githubusercontent.com/45259624/75514910-9baf2480-5a33-11ea-8315-9262cb569988.png)

**Comment by Ameykyl** [comment]
gfw模式暂时没发现问题 我的正常打开
