### ISSUE TITLE
Jo,全新不保留配置刷机后，vssr的chinaDNS处于自动运行状态，正常吗？

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#18]
![9K {{%ZJ1}~CDRU$D9WI4U1](https://user-images.githubusercontent.com/45259624/75976298-218c0d80-5f15-11ea-9e3d-8d6be8db1d03.png)

**Comment by Ameykyl** [comment]
你是不是开启了udp

**Comment by zxlhhyccc** [comment]
> 你是不是开启了udp

没有开启udp，我升级是未保留配置，刷完后直接进入插件，显示运行中。。。

**Comment by Ameykyl** [comment]
看看有没程序运行 这个不打紧运行也没事   暂时没发现关闭所有服务还是开启的
