### ISSUE TITLE
Jo，提个bug，经测试，使用dnscrypt-proxy查询并缓存，无法正常翻墙！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#2]
![PPM6)T{GVI17(ZR@CB O(_E](https://user-images.githubusercontent.com/45259624/75054036-3fb53f00-550d-11ea-82af-e8626b3ca455.png)

**Comment by zxlhhyccc** [comment]
应该是已找到原因，源码包缺失文件。。。。

**Comment by Ameykyl** [comment]
https://github.com/Leo-Jo-My/my 用这个里面的文件编译
