### ISSUE TITLE
Jo,最新版本使用dnscrypt_proxy不能运行解析dns，导致不能科学！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#21]
![image](https://user-images.githubusercontent.com/45259624/76708235-4ad84500-6730-11ea-8538-90ef9b779107.png)
系统日志报错：
![image](https://user-images.githubusercontent.com/45259624/76709816-bcb68b80-673c-11ea-86e1-3b554457955f.png)

**Comment by Ameykyl** [comment]
用上次我发你包编译  不通就是配置文件有问题

**Comment by zxlhhyccc** [comment]
> 用上次我发你包编译 不通就是配置文件有问题

你上次发的包中，init有问题，使用2.0.36的init可以正常运行，但是不能使用在最新vssr上运行，vssr我降级到20200309版本正常。。。。
还有就是，2.0.36版本的init和你发的init代码一样，但大小不一样，可能有什么东东在里面。。。

**Comment by Ameykyl** [comment]
etc/init.d/dnscrypt-proxy  给权限0755

**Comment by zxlhhyccc** [comment]
> etc/init.d/dnscrypt-proxy 给权限0755

给了权限没用。。。。
