### ISSUE TITLE
Jo，没启用dns情况下dns仍然运行的严重bug！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#22]
今日无意中发现：
1、选择chinaDNS或者dns2socks解析dns时，实际两者均不运行，运行的是dnscrypt-proxy或者dnsforwarder；
2、启动dnscrypt-proxy或者dnsforwarder后切换到chinaDNS或者dns2socks解析，运行的仍然是dnscrypt-proxy或者dnsforwarder；
3、启动dnscrypt-proxy或者dnsforwarder后停止vssr，但是dnscrypt-proxy或者dnsforwarder仍然显示正常运行；
![5Z6Z@3CCIN~0~73 _7OFOAW](https://user-images.githubusercontent.com/45259624/77078231-431ae800-6a31-11ea-950b-1d67c5bbeb83.png)
![J JRVL6@PTX2`XQ_@WPG5}T](https://user-images.githubusercontent.com/45259624/77078300-5b8b0280-6a31-11ea-9865-71afdafc64fa.png)

**Comment by Ameykyl** [comment]
切换到pd在换其他  某个进程没kill
