### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by fuqiang03** [Leo-Jo-My/luci-app-vssr#23]
sh: 3: unknown operand
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:01:15 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:01:21 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:01:21 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:01:21 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:01:21 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:01:28 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:01:28 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:01:28 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:01:28 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:03:29 2020 daemon.err uhttpd[4990]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Thu Mar 26 22:03:29 2020 daemon.err uhttpd[4990]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Thu Mar 26 22:03:43 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:03:43 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:03:43 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:03:43 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:04:05 2020 daemon.err uhttpd[4990]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Thu Mar 26 22:04:05 2020 daemon.err uhttpd[4990]: Another app is currently holding the xtables lock. Perhaps you want to use the -w option?
Thu Mar 26 22:05:07 2020 authpriv.info dropbear[17101]: Child connection from 192.168.1.5:53883
Thu Mar 26 22:05:08 2020 authpriv.notice dropbear[17101]: Auth succeeded with blank password for 'root' from 192.168.1.5:53883
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: Name does not resolve
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: stack traceback:
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: 	[C]: in function 'lookup'
Thu Mar 26 22:07:16 2020 daemon.err uhttpd[4990]: 	/usr/lib/lua/luci/controller/vssr.lua:425: in function </usr/lib/lua/luci/controller/vssr.lua:418>
Thu Mar 26 22:07:26 2020 daemon.err uhttpd[4990]: Name does not resolve

**Comment by Ameykyl** [comment]
这个和你使用的固件版本有关，是基于18.06改的 日志有错误不影响使用不必在意这个

**Comment by fuqiang03** [comment]
谢谢
