### ISSUE TITLE
make menuconfig时跳出错误

### ISSUE THREAD

**Issue by jinjin327** [Leo-Jo-My/luci-app-vssr#24]
Collecting package info: done
tmp/.config-package.in:85051:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:85051:   symbol PACKAGE_v2ray-plugin is selected by PACKAGE_v2ray-plugin
tmp/.config-package.in:79572:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:79572:   symbol PACKAGE_dnsforwarder is selected by PACKAGE_luci-app-dnsforwarder
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:47755:   symbol PACKAGE_luci-app-dnsforwarder depends on PACKAGE_dnsforwarder
tmp/.config-package.in:84180:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:84180:   symbol PACKAGE_simple-obfs is selected by PACKAGE_simple-obfs
tmp/.config-package.in:84210:error: recursive dependency detected!
For a resolution refer to Documentation/kbuild/kconfig-language.txt
subsection "Kconfig recursive dependency limitations"
tmp/.config-package.in:84210:   symbol PACKAGE_simple-obfs-server is selected by PACKAGE_simple-obfs-server
configuration written to .config

**Comment by Ameykyl** [comment]
这个不影响编译    有些依赖和lean 用的不一样去my包拉取替换lean目录的包编译luci-app-dnsforwarder这个不要编译
