### ISSUE TITLE
Vssr里的UDPspeeder和UDP2raw的部分栏位没有汉化，能否加以汉化？？？！！！

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#4]
![Q62`V_59P@8RD7CK59S9C}4](https://user-images.githubusercontent.com/45259624/75087182-f3ebaf80-5577-11ea-83d9-6e474b8d4eba.png)

**Comment by Ameykyl** [comment]
你可以在po文件里面加自己汉化下
