### ISSUE TITLE
jo，lean的ssrplus+增加了trojan的多线程支持，能否更新一下？第二，插件里的“HaProxy 设置”启用不启用无关紧要，仅用luci也是可以。

### ISSUE THREAD

**Issue by zxlhhyccc** [Leo-Jo-My/luci-app-vssr#8]
![image](https://user-images.githubusercontent.com/45259624/75215066-86838d00-57ca-11ea-9aed-1a8c9ab9ef85.png)

**Comment by Ameykyl** [comment]
已更新
